#!/usr/bin/env python3
"""Generate docs/DATA_DICTIONARY.md from the schema and the PHI classification.

Generated rather than written, for one reason: a hand-maintained data
dictionary is accurate on the day it is written and misleading within a month.
This one is derived from ``sql/star_schema.sql`` and
``hourglass.phi.FIELD_CLASSIFICATION``, so a column added without being
classified shows up here as a gap, and the same gap blocks the pipeline.

    python scripts/build_data_dictionary.py
"""

from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hourglass import phi  # noqa: E402
from hourglass.config import SERVICES, WAREHOUSE  # noqa: E402

SCHEMA = ROOT / "sql" / "star_schema.sql"
OUTPUT = ROOT / "docs" / "DATA_DICTIONARY.md"

SENSITIVITY_NOTE = {
    "direct_identifier": "**Never published raw.** Pseudonymised on export.",
    "quasi_identifier": "Published, but generalised where it can be.",
    "clinical": "Health information. Published only alongside pseudonymised keys.",
    "operational": "About the business, not the person.",
    "safe": "Reference data with no link to an individual.",
}

UNSTABLE_COUNTS = {"run_log"}
"""Tables whose row count is not a function of the data, and so must not be
written into a file that CI compares byte-for-byte against a regeneration."""


LINEAGE = {
    "dim_client": "salesforce_clients.csv → `build_dim_client` (SCD Type 2)",
    "dim_provider": "reference_providers.csv → `build_dim_provider`",
    "dim_center": "reference_centers.csv → `build_dim_center`",
    "dim_payer": "reference_payers.csv → `build_dim_payer`",
    "dim_service": "`config.SERVICES` → `build_dim_service`",
    "dim_date": "derived from the observed date range → `build_dim_date`",
    "fact_session": "ehr_sessions.csv → `dedupe_sessions` → `resolve_minutes` "
                    "→ `build_fact_session`",
    "fact_authorization": "payer_authorizations.csv → `build_fact_authorization`",
    "run_log": "written by `model.atomic_build` on every run",
    "etl_watermark": "written by `incremental.load_incrementally`",
}


def parse_grain_comments(ddl: str) -> dict[str, str]:
    """Pull the ``-- GRAIN:`` line that precedes each CREATE TABLE.

    Reading the grain out of the DDL rather than restating it here means the
    two cannot disagree. If somebody changes a table's grain and forgets the
    comment, this document says so by leaving it blank.
    """
    grains: dict[str, str] = {}
    pending: list[str] = []
    for line in ddl.splitlines():
        stripped = line.strip()
        if stripped.upper().startswith("-- GRAIN:"):
            pending = [stripped[len("-- GRAIN:"):].strip()]
        elif pending and stripped.startswith("--"):
            pending.append(stripped.lstrip("- ").strip())
        elif match := re.match(r"CREATE TABLE(?: IF NOT EXISTS)? (\w+)", stripped, re.I):
            if pending:
                grains[match.group(1)] = " ".join(pending)
            pending = []
        elif stripped and not stripped.startswith("--"):
            pending = []
    return grains


def column_types(ddl: str) -> dict[str, dict[str, str]]:
    """Column names and declared types, straight from the DDL."""
    tables: dict[str, dict[str, str]] = {}
    current: str | None = None
    for line in ddl.splitlines():
        stripped = line.strip()
        if match := re.match(r"CREATE TABLE(?: IF NOT EXISTS)? (\w+)", stripped, re.I):
            current = match.group(1)
            tables[current] = {}
            continue
        if current is None:
            continue
        if stripped.startswith(")"):
            current = None
            continue
        if match := re.match(r"(\w+)\s+(INTEGER|TEXT|REAL|BLOB|NUMERIC)", stripped, re.I):
            tables[current][match.group(1)] = match.group(2).upper()
    return tables


def row_counts() -> dict[str, int]:
    if not WAREHOUSE.exists():
        return {}
    conn = sqlite3.connect(WAREHOUSE)
    try:
        names = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table'").fetchall()]
        return {n: conn.execute(f"SELECT COUNT(*) FROM {n}").fetchone()[0]
                for n in names}
    finally:
        conn.close()


def build() -> str:
    ddl = SCHEMA.read_text(encoding="utf-8")
    grains, types, counts = parse_grain_comments(ddl), column_types(ddl), row_counts()

    out: list[str] = []
    add = out.append

    add("# Data dictionary")
    add("")
    add("*Generated by `scripts/build_data_dictionary.py`. Do not edit by hand —*")
    add("*edit `sql/star_schema.sql` or `hourglass.phi.FIELD_CLASSIFICATION` and*")
    add("*regenerate. A hand-maintained dictionary is accurate the day it is*")
    add("*written and misleading a month later.*")
    add("")
    add("Every column carries a data-protection classification. That column is not")
    add("documentation: `hourglass.phi.check_egress` reads the same table, and a")
    add("column that is missing from it or classified as a direct identifier will")
    add("stop the pipeline from publishing. **All data described here is synthetic.**")
    add("")

    add("## Classifications")
    add("")
    add("| Classification | Meaning |")
    add("|---|---|")
    for value, note in SENSITIVITY_NOTE.items():
        add(f"| `{value}` | {note} |")
    add("")
    add("A column absent from the classification table is treated as a direct")
    add("identifier. Unknown is not safe, and the default has to fail loudly.")
    add("")

    for table in sorted(types):
        add("---")
        add("")
        add(f"## `{table}`")
        add("")
        if grain := grains.get(table):
            add(f"**Grain.** {grain}")
            add("")
        if lineage := LINEAGE.get(table):
            add(f"**Lineage.** {lineage}")
            add("")
        # `run_log` is deliberately excluded. It is append-only across every
        # run a machine has ever done, so its row count is a property of that
        # machine's history rather than of the data -- 176 on one checkout, 1
        # on a fresh clone. The CI step that regenerates this file and runs
        # `git diff --exit-code` would therefore fail on every run, for a
        # difference that means nothing, and a guard that always fails is a
        # guard everyone learns to ignore.
        if table in counts and table not in UNSTABLE_COUNTS:
            add(f"**Rows in the current warehouse.** {counts[table]:,}")
            add("")
        elif table in UNSTABLE_COUNTS:
            add("**Rows.** Grows by one per pipeline run and is never "
                "truncated, so the count is a property of this machine's run "
                "history rather than of the data. Omitted here so the "
                "generated file is reproducible.")
            add("")

        add("| Column | Type | Classification | Note |")
        add("|---|---|---|---|")
        declared = phi.FIELD_CLASSIFICATION.get(table, {})
        for column, sql_type in types[table].items():
            if table in phi.FIELD_CLASSIFICATION and column not in declared:
                classification = "**UNCLASSIFIED**"
                note = "⚠️ Not declared. This blocks publication until classified."
            elif table not in phi.FIELD_CLASSIFICATION:
                classification = "n/a"
                note = "Internal table; never published."
            else:
                sensitivity = declared[column]
                classification = f"`{sensitivity.value}`"
                note = SENSITIVITY_NOTE[sensitivity.value]
            add(f"| `{column}` | {sql_type} | {classification} | {note} |")
        add("")

    add("---")
    add("")
    add("## Service catalogue")
    add("")
    add("`minutes_per_unit` is the reason `dim_service` exists. A \"unit\" is not a")
    add("fixed quantity of time, so a units column cannot be summed across service")
    add("codes without this conversion — and every hours figure in the project,")
    add("Python, SQL and DAX alike, converts through it.")
    add("")
    add("| Code | Service | Discipline | Unit basis | Minutes per unit |")
    add("|---|---|---|---|---:|")
    for service in SERVICES:
        add(f"| `{service['service_code']}` | {service['service_name']} "
            f"| {service['discipline']} | `{service['unit_basis']}` "
            f"| {service['minutes_per_unit']} |")
    add("")

    add("---")
    add("")
    add("## What is deliberately not modelled")
    add("")
    add("- **Authorisation amendments.** Authorisations are modelled as issued, not")
    add("  as revised. Real payers amend them, and a Type 2 `fact_authorization`")
    add("  would be the way to carry that.")
    add("- **Session start times.** The source has none, which is why the")
    add("  deduplication key cannot distinguish a genuine second visit on the same")
    add("  day from a double entry. See `transform.dedupe_sessions`.")
    add("- **Provider history.** `dim_provider` is Type 1; corrections overwrite.")
    add("  Client history is load-bearing for payer attribution, provider history is")
    add("  not, and the complexity was not worth it here.")
    add("")
    return "\n".join(out)


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")

    # Regenerating is cheap; noticing an unclassified column late is not.
    missing = {
        table: phi.undeclared_columns(table, columns)
        for table, columns in column_types(SCHEMA.read_text(encoding="utf-8")).items()
        if table in phi.FIELD_CLASSIFICATION
        and phi.undeclared_columns(table, columns)
    }
    if missing:
        print("\nUNCLASSIFIED COLUMNS — these will block publication:")
        for table, columns in missing.items():
            print(f"  {table}: {', '.join(columns)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
